### PR TITLE
[DO NOT MERGE] Preparations for v4.2.6

### PR DESCRIPTION
**Pull request by guihkx**
More details in the commit's description.

The Flathub bot will automatically open a pull request here after you release v4.2.6, but the build will not succeed. So, this PR should be used instead.

I have notifications enabled for new releases of RSS Guard, but feel free to ping me once v4.2.6 is out and I'll update this PR as soon as I can.

### CODE REVIEW

**Comment by guihkx** [comment]
The build should pass once https://github.com/flathub/flatpak-builder-lint/pull/100 gets merged.

**Comment by martinrotter** [comment]
I plan to release 4.2.6 and THEN merge https://github.com/martinrotter/rssguard/pull/836

OK? Releasing in one two days.

**Comment by guihkx** [comment]
I actually have one more commit to push to that PR, and it's to use the correct app id when building via GitHub Actions.

After that, merging should be good.

**Comment by guihkx** [comment]
@martinrotter Do you have any preference about which Qt version to use? Should I just stay on 6.3, or should I bump it to 6.4?

**Comment by guihkx** [comment]
I'll set the PR ready for review once 4.2.7 is released and it builds with no issues.

**Comment by guihkx** [comment]
Actually, we decided in https://github.com/martinrotter/rssguard/pull/836#issuecomment-1361355016 to release 4.2.7 under the new app ids (soon to be submitted by me to Flathub).

@martinrotter I'll close this PR then, and you can close #35. And once the two new app ids get accepted into Flathub, I'll send a PR deprecating this old app id. Sound good?!

**Pull request closed without merging**
