### PR TITLE
update to 3.5.6

### PR DESCRIPTION
**Pull request by nedrichards**

### CODE REVIEW

**Comment by nedrichards** [comment]
bot, build

**Comment by snj33v** [comment]
can you update qt sdk version too

**Comment by nedrichards** [comment]
@snj33v what about 5.10 is better/does it need?

**Comment by martinrotter** [comment]
@nedrichards RSS Guard itself does not need any Qt 5.10 specific functionality, it will build with 5.7.0+.
@grulja Should be Qt SDK version be increased to 5.10 (I have no idea how exactly flatpak SDKs work). Maybe other flathub apps use 5.10 so it would make sense to use 5.10 for RSS Guard too so that users do not have to have 5.9 installed just for one app.

**Comment by grulja** [comment]
I think most apps still use Qt 5.9 (because it's an LTS release) so if there is no reason jump to Qt 5.10, then stick with Qt 5.9.

**Comment by martinrotter** [comment]
Done.

**Pull request merged**
