### PR TITLE
Release 4.2.2

### LINKED ISSUE #24: Web engine version?
Would it be possible to have the web engine enabled version instead of the lite version?

https://github.com/martinrotter/rssguard/blob/master/resources/docs/Documentation.md#webb

### PR DESCRIPTION
**Pull request by guihkx**
- Convert JSON manifest to YAML for easier readability and maintainability
- Build with QWebEngine enabled by default
- Bundle NodeJS and npm for Adblock support
- Manifest auto-update support using [external-data-checker](https://github.com/flathub/flatpak-external-data-checker#readme)

Closes #24

---

Adblock OFF:

Adblock ON:

### CODE REVIEW

**Comment by martinrotter** [comment]
Wow, nice. Let me quick test.

**Comment by martinrotter** [comment]
@guihkx Just quiestion, is there any flatpak-specific stuff I would need to possibly tweak in build time? Like disable some functionality which is "by design" unavailable in flatpak environment etc.? Just to improve user experience...

**Comment by martinrotter** [comment]
@guihkx Just tested, seems to work perfectly, merging.

**Comment by martinrotter** [comment]
Thank you too!

**Comment by guihkx** [comment]
>is there any flatpak-specific stuff I would need to possibly tweak in build time?

I don't think so...

But I'm aware that RSS Guard has so many cool features, but at the same time my use-case is pretty simple, so I'm not 100% sure if *everything* works.

The only thing I'm aware that doesn't work properly is importing/exporting feeds from an OPML file.

If I could suggest a change, it would be a compile flag to disable checking for updates altogether, which doesn't make sense for Flatpak users.

**Comment by martinrotter** [comment]
> If I could suggest a change, it would be a compile flag to disable checking for updates altogether, which doesn't make sense for Flatpak users.

Turn that into FR ticket in rssguard repo pls!

Also, I noticed that RSS Guard does not show it's name in "taskbar".

image

there is only "as superuser"...

weird

**Comment by martinrotter** [comment]
Only interesting strings from log are:

```
Note that the directories 

'/var/lib/flatpak/exports/share'
'/home/martin/.local/share/flatpak/exports/share'

are not in the search path set by the XDG_DATA_DIRS environment variable, so
applications installed by Flatpak may not appear on your desktop until the
session is restarted.

Gtk-Message: 20:33:05.469: Failed to load module "canberra-gtk-module"
time="     0.089" type="warning" -> Qt: Session management error: None of the authentication protocols specified are supported
```

This is Arch with X11 btw.

**Comment by guihkx** [comment]
LOL, what the heck.

We're not even supposed to run Flatpak app as root, so I'm not exactly sure what's going on there.

Regarding the second warning, did you just install Flatpak and did not reboot?

There's a file in `/etc/profile.d/flatpak.sh` which is supposed to be sourced by the display manager and those directories will be automatically added to `XDG_DATA_DIRS`.

**Comment by martinrotter** [comment]
I dont know, I just did

`flatpak run --user com.github.rssguard -w`

**Comment by martinrotter** [comment]
@guihkx Rebooted, still shows that weird "as superuser" only and no title. :D

**Comment by martinrotter** [comment]
@guihkx It seems to be MATE-related "bug".

https://github.com/flatpak/flatpak/issues/1557

**Comment by guihkx** [comment]
Ugh... What a strange bug, though. lol

**Comment by martinrotter** [comment]
Just tested with AppImage build and that one shows "RSS Guard" title in taskbar correctly, but on the other hand its QtWebEngine component does not seem to work at all. WTF.

**Comment by guihkx** [comment]
I'm on Arch too, and the 4.2.2 WebEngine AppImage build works fine for me.

It could be possible that the WebEngine AppImage requires some system library that you don't have installed, so maybe try running the AppImage using the terminal to spot some error...

**Pull request merged**
