### PR TITLE
Update com.github.rssguard.json

### PR DESCRIPTION
**Pull request by martinrotter**

### CODE REVIEW

**Comment by martinrotter** [comment]
@grulja or somebody else. Build fails with

```
CMake Error at /usr/lib/aarch64-linux-gnu/cmake/Qt5/Qt5Config.cmake:28 (find_package):
  Could not find a package configuration file provided by
  "Qt5WebEngineWidgets" with any of the following names:
    Qt5WebEngineWidgetsConfig.cmake
    qt5webenginewidgets-config.cmake
```

Is there a way to "enable" WebEngine module on Flathub?

**Comment by guihkx** [comment]
Does this mean that starting from version 4.2, RSS Guard will use the WebEngine build by default?

If so, is there any way to disable WebEngine at runtime, with a switch or something?

**Comment by martinrotter** [comment]
@guihkx No, one can easily switch webengine off with `-DUSE_WEBENGINE=OFF` flag.

Are you implying that older RSS Guard flatpaks are in fact "nowebengine" builds? I don't know, do not use those. If so, then simply flag above will solve the problem.

**Comment by guihkx** [comment]
>Are you implying that older RSS Guard flatpaks are in fact "nowebengine" builds?

Yup, I'm using the Flatpak version and there's no Webengine here:

image

I've switched to the Flatpak version, because the official packager of RSS Guard on Arch Linux is, unfortunately, taking way too long to update it.

**Pull request merged**
